# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBIgGXTIusWQlqtj3oKnBsU9BlmZhUbK
"""

my_tasks = []

my_tasks.append("Finish Python assignment")
my_tasks.append("Buy Milk")
my_tasks.append("Walk Dog")

for task in my_tasks:
    print(task)

for index, task in enumerate(my_tasks):
    print(f"{index + 1}. {task}")

def show_menu():
    """Displays the menu options to the user."""
    print("\n--- TO-DO LIST MENU ---")
    print("1. Add a task")
    print("2. View all tasks")
    print("3. Exit")


def add_task(task_list):
    """Asks the user for a task and adds it to the list."""
    new_task = input("Enter the task you want to add: ")
    task_list.append(new_task)
    print(f'"{new_task}" was added to your list.')


def view_tasks(task_list):
    """Displays all tasks currently in the list."""
    if not task_list:  # checks if the list is empty
        print("Your to-do list is empty!")
        return

    print("\n--- YOUR TASKS ---")
    for index, task in enumerate(task_list):
        print(f"{index + 1}. {task}")


def main():
    my_tasks = []  # our list acts as temporary storage (in RAM)

    while True:
        show_menu()
        choice = input("Choose an option (1-3): ")

        if choice == "1":
            add_task(my_tasks)
        elif choice == "2":
            view_tasks(my_tasks)
        elif choice == "3":
            print("Goodbye! Your session has ended.")
            break
        else:
            print("Invalid choice, please try again.")


if __name__ == "__main__":
    main()