# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rumPYXChH808cfGEmf87k7xF2EGVThEk
"""

# ============================================================
# DECODELABS - PYTHON PROGRAMMING
# PROJECT 2: EXPENSE TRACKER
# ============================================================

print("==========================================")
print("          DECODELABS PROJECT 2")
print("             EXPENSE TRACKER")
print("==========================================")

# Initialize total expense
total = 0

# Keep asking the user for expenses
while True:

    # Take expense from the user
    expense = input("\nEnter expense amount (or type 'done' to finish): ")

    # Stop the program when user enters done
    if expense.lower() == "done":
        break

    # Convert the input into a number
    try:
        expense = float(expense)

        # Check that the expense is not negative
        if expense < 0:
            print("Error: Expense cannot be negative.")
            continue

        # Add the new expense to the total
        total = total + expense

        # Display the updated total
        print("Expense added successfully!")
        print("Current Total Spent:", total)

    # Handle invalid input
    except ValueError:
        print("Invalid input! Please enter a valid number.")

# Display the final total
print("\n==========================================")
print("             EXPENSE SUMMARY")
print("==========================================")
print("Total Spent:", total)
print("==========================================")
print("Thank you for using Expense Tracker!")