# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rumPYXChH808cfGEmf87k7xF2EGVThEk
"""

"""
Project 1: The To-Do List
DecodeLabs — Python Programming Industrial Training Kit (Batch 2026)

Goal: Build a program where users can add tasks to a list and view them.
Key Skill: Lists (append & print loops), enumerate(), and basic persistence.
"""

import json
import os

TASKS_FILE = "tasks.json"


def load_tasks():
    """Load tasks from disk if a saved file exists, otherwise start fresh."""
    if os.path.exists(TASKS_FILE):
        with open(TASKS_FILE, "r") as f:
            return json.load(f)
    return []


def save_tasks(my_tasks):
    """Persist tasks to disk (Storage), since RAM is volatile."""
    with open(TASKS_FILE, "w") as f:
        json.dump(my_tasks, f, indent=2)


def add_task(my_tasks):
    """Input: get a new task from the user and append it to the list."""
    task = input("Enter a new task: ").strip()
    if task:
        my_tasks.append(task)
        print(f'Added: "{task}"')
    else:
        print("Task cannot be empty.")


def view_tasks(my_tasks):
    """Output: display all tasks using enumerate() for index + value."""
    if not my_tasks:
        print("Your to-do list is empty.")
        return
    print("\n--- Your To-Do List ---")
    for index, task in enumerate(my_tasks, start=1):
        print(f"{index}. {task}")
    print("------------------------\n")


def delete_task(my_tasks):
    """Process: remove a task by its displayed number."""
    view_tasks(my_tasks)
    if not my_tasks:
        return
    try:
        choice = int(input("Enter the task number to delete: "))
        if 1 <= choice <= len(my_tasks):
            removed = my_tasks.pop(choice - 1)
            print(f'Removed: "{removed}"')
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")


def show_menu():
    print("=" * 30)
    print(" DECODELABS TO-DO LIST")
    print("=" * 30)
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Delete Task")
    print("4. Exit")


def main():
    my_tasks = load_tasks()

    while True:
        show_menu()
        choice = input("Choose an option (1-4): ").strip()

        if choice == "1":
            add_task(my_tasks)
            save_tasks(my_tasks)
        elif choice == "2":
            view_tasks(my_tasks)
        elif choice == "3":
            delete_task(my_tasks)
            save_tasks(my_tasks)
        elif choice == "4":
            save_tasks(my_tasks)
            print("Tasks saved. Goodbye!")
            break
        else:
            print("Invalid choice. Please select 1-4.\n")


if __name__ == "__main__":
    main()