# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rumPYXChH808cfGEmf87k7xF2EGVThEk
"""

# ============================================================
# DECODELABS - PYTHON PROGRAMMING
# PROJECT 3: RANDOM PASSWORD GENERATOR
# ============================================================

import random
import string

print("==========================================")
print("          DECODELABS PROJECT 3")
print("        RANDOM PASSWORD GENERATOR")
print("==========================================")

# Ask the user for password length
while True:
    try:
        length = int(input("\nEnter password length: "))

        if length < 4:
            print("Password length must be at least 4 characters.")
            continue

        break

    except ValueError:
        print("Invalid input! Please enter a whole number.")

# Character groups
letters = string.ascii_letters
numbers = string.digits
special_characters = "@#$%&*!?"

# Make sure the password contains at least:
# 1 letter, 1 number, and 1 special character
password = [
    random.choice(letters),
    random.choice(numbers),
    random.choice(special_characters)
]

# Remaining characters
all_characters = letters + numbers + special_characters

for i in range(length - 3):
    password.append(random.choice(all_characters))

# Shuffle the characters
random.shuffle(password)

# Convert list into a string
password = "".join(password)

# Display result
print("\n==========================================")
print("          PASSWORD GENERATED")
print("==========================================")
print("Your random password is:", password)
print("Password length:", len(password))
print("==========================================")