# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rumPYXChH808cfGEmf87k7xF2EGVThEk
"""

"""
Python Programming - Industrial Training Kit
Project 4: The General Knowledge Quiz

Goal:
    Ask 3 general knowledge questions, keep a running score
    (+1 point per correct answer), and print the final score
    at the end.

Key Skill:
    If-Else logic & Variables (Control Flow)

Design notes (per project spec):
    - Every answer goes through a sanitization pipeline: .strip().lower()
      so that extra whitespace and inconsistent capitalization don't
      cause a correct answer to be marked wrong.
    - score is initialized as an integer (score = 0) and incremented
      with score += 1 only on a correct match — the else branch performs
      no operation on the score (state is maintained, not reset).
    - The final result is delivered using an f-string.
"""

# ------------------------------------------------------------------
# STORAGE: State Initialization
# ------------------------------------------------------------------
score = 0  # integer accumulator — the "Score Vault"

# ------------------------------------------------------------------
# The Question Bank
# Each question is paired with its reference (correct) answer.
# ------------------------------------------------------------------
questions = [
    {
        "question": "What is the capital of France? ",
        "answer": "paris"
    },
    {
        "question": "What is the largest planet in our Solar System? ",
        "answer": "jupiter"
    },
    {
        "question": "Who wrote the play 'Romeo and Juliet'? ",
        "answer": "shakespeare"
    },
]


def run_quiz():
    """Runs the General Knowledge Quiz and returns the final score."""
    global score

    print("=" * 50)
    print("WELCOME TO THE GENERAL KNOWLEDGE QUIZ!")
    print("=" * 50)
    print("Answer each question below. Good luck!\n")

    # ----------------------------------------------------------------
    # Repeatable Question Block (Ask -> Sanitize -> Evaluate -> Execute)
    # ----------------------------------------------------------------
    for i, q in enumerate(questions, start=1):

        # Step 1: Ask & Capture — prompt via input() and store raw string
        raw_input_answer = input(f"Q{i}: {q['question']}")

        # Step 2: Sanitize — apply filter pipeline: .strip().lower()
        guess = raw_input_answer.strip().lower()

        # Step 3: Evaluate — compare sanitized input against reference solution
        # Step 4: Execute — route through If-Else gate to trigger side effects
        if guess == q["answer"]:
            score += 1  # correct: increment score
            print("Correct! ✅\n")
        else:
            # Failure case: no operation on score, state is maintained
            print(f"Wrong! ❌ The correct answer was '{q['answer'].title()}'.\n")

    # ----------------------------------------------------------------
    # Output: Deliver the final result with an f-string
    # ----------------------------------------------------------------
    total = len(questions)
    print("=" * 50)
    print(f"Quiz complete! Your final score is {score:>2}/{total}.")
    print("=" * 50)

    return score


if __name__ == "__main__":
    run_quiz()